### ISSUE TITLE
getDomain('http://a.np') returns null

### ISSUE THREAD

**Issue by MarcCoquand** [thom4parisot/tld.js#141]
Version: 2.3.1

When running `getDomain('http://a.np')`, I expected `'a.np'` but received instead `null`.

EDIT:

Also, `getDomain('http://a.se') -> null` but `getDomain('http://a.de') -> 'a.de'`

**Comment by remusao** [comment]
Hi @MarcCoquand,

This behavior is expected and it might be a bit clearer when looking at the output of `parse` for each of the domains.

`https://a.np`:
```sh
$ npx tldts http://a.np
{
  "domain": null,
  "domainWithoutSuffix": null,
  "hostname": "a.np",
  "isIcann": true,
  "isIp": false,
  "isPrivate": false,
  "publicSuffix": "a.np",
  "subdomain": null
}
```

`http://a.se`:
```sh
$ npx tldts http://a.se
{
  "domain": null,
  "domainWithoutSuffix": null,
  "hostname": "a.se",
  "isIcann": true,
  "isIp": false,
  "isPrivate": false,
  "publicSuffix": "a.se",
  "subdomain": null
}
```

Both `a.se` and `a.np` are public suffixes, which means they cannot be "registered domains" or "TLD+1". On the other hand: `https://a.b.se` would have domain `a.b.np` and public suffix `b.np`. The exact entry in the public suffix list is the following:

```
// np : http://www.mos.com.np/register.html
*.np
```

This means that any label followed by `np` is a valid public suffix.

I hope this helps,
Best,
Rémi
